-- VOXA — full database setup for a fresh Supabase project.
-- Paste this entire file into the Supabase SQL Editor and run once.
-- Generated by concatenating supabase/migrations/*.sql in order.


-- ============================================================
-- migrations/20260630194046_8fbddd7e-8204-4984-8096-27e2d1745f02.sql
-- ============================================================

-- Roles
CREATE TYPE public.app_role AS ENUM ('admin', 'user');

CREATE TABLE public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  display_name TEXT,
  avatar_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.profiles TO authenticated;
GRANT ALL ON public.profiles TO service_role;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "profiles_self_read" ON public.profiles FOR SELECT TO authenticated USING (auth.uid() = id);
CREATE POLICY "profiles_self_update" ON public.profiles FOR UPDATE TO authenticated USING (auth.uid() = id);
CREATE POLICY "profiles_self_insert" ON public.profiles FOR INSERT TO authenticated WITH CHECK (auth.uid() = id);

CREATE TABLE public.user_roles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role public.app_role NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, role)
);
GRANT SELECT ON public.user_roles TO authenticated;
GRANT ALL ON public.user_roles TO service_role;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "user_roles_self_read" ON public.user_roles FOR SELECT TO authenticated USING (auth.uid() = user_id);

CREATE OR REPLACE FUNCTION public.has_role(_user_id UUID, _role public.app_role)
RETURNS BOOLEAN LANGUAGE SQL STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = _user_id AND role = _role)
$$;

-- Plans
CREATE TABLE public.plans (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  price_monthly NUMERIC(10,2) NOT NULL DEFAULT 0,
  char_quota BIGINT NOT NULL DEFAULT 0,
  audio_seconds_quota BIGINT NOT NULL DEFAULT 0,
  features JSONB NOT NULL DEFAULT '[]'::jsonb,
  display_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT ON public.plans TO authenticated, anon;
GRANT ALL ON public.plans TO service_role;
ALTER TABLE public.plans ENABLE ROW LEVEL SECURITY;
CREATE POLICY "plans_public_read" ON public.plans FOR SELECT TO authenticated, anon USING (true);
CREATE POLICY "plans_admin_write" ON public.plans FOR ALL TO authenticated
  USING (public.has_role(auth.uid(), 'admin')) WITH CHECK (public.has_role(auth.uid(), 'admin'));

-- Subscriptions
CREATE TABLE public.subscriptions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  plan_id TEXT NOT NULL REFERENCES public.plans(id),
  status TEXT NOT NULL DEFAULT 'active',
  current_period_start TIMESTAMPTZ NOT NULL DEFAULT now(),
  current_period_end TIMESTAMPTZ NOT NULL DEFAULT (now() + interval '30 days'),
  stripe_subscription_id TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT ON public.subscriptions TO authenticated;
GRANT ALL ON public.subscriptions TO service_role;
ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "subs_self_read" ON public.subscriptions FOR SELECT TO authenticated
  USING (auth.uid() = user_id OR public.has_role(auth.uid(), 'admin'));

-- Voices
CREATE TABLE public.voices (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  elevenlabs_id TEXT NOT NULL UNIQUE,
  tone TEXT,
  preview_text TEXT DEFAULT 'Hello, I am your new voice agent.',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT ON public.voices TO authenticated;
GRANT ALL ON public.voices TO service_role;
ALTER TABLE public.voices ENABLE ROW LEVEL SECURITY;
CREATE POLICY "voices_read_auth" ON public.voices FOR SELECT TO authenticated USING (true);
CREATE POLICY "voices_admin_write" ON public.voices FOR ALL TO authenticated
  USING (public.has_role(auth.uid(), 'admin')) WITH CHECK (public.has_role(auth.uid(), 'admin'));

-- Bot personalities
CREATE TABLE public.bot_personalities (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  description TEXT,
  system_prompt TEXT NOT NULL,
  voice_id UUID REFERENCES public.voices(id) ON DELETE SET NULL,
  temperature NUMERIC(3,2) NOT NULL DEFAULT 0.7,
  avatar_emoji TEXT DEFAULT 'V',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.bot_personalities TO authenticated;
GRANT ALL ON public.bot_personalities TO service_role;
ALTER TABLE public.bot_personalities ENABLE ROW LEVEL SECURITY;
CREATE POLICY "personas_owner_all" ON public.bot_personalities FOR ALL TO authenticated
  USING (auth.uid() = user_id OR public.has_role(auth.uid(), 'admin'))
  WITH CHECK (auth.uid() = user_id);

-- Conversations
CREATE TABLE public.conversations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  personality_id UUID REFERENCES public.bot_personalities(id) ON DELETE SET NULL,
  title TEXT NOT NULL DEFAULT 'New conversation',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.conversations TO authenticated;
GRANT ALL ON public.conversations TO service_role;
ALTER TABLE public.conversations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "conv_owner_all" ON public.conversations FOR ALL TO authenticated
  USING (auth.uid() = user_id OR public.has_role(auth.uid(), 'admin'))
  WITH CHECK (auth.uid() = user_id);

-- Messages
CREATE TABLE public.messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_id UUID NOT NULL REFERENCES public.conversations(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role TEXT NOT NULL CHECK (role IN ('user','assistant','system')),
  content TEXT NOT NULL,
  audio_url TEXT,
  char_count INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.messages TO authenticated;
GRANT ALL ON public.messages TO service_role;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "msg_owner_all" ON public.messages FOR ALL TO authenticated
  USING (auth.uid() = user_id OR public.has_role(auth.uid(), 'admin'))
  WITH CHECK (auth.uid() = user_id);
CREATE INDEX msg_conv_idx ON public.messages(conversation_id, created_at);

-- Usage logs
CREATE TABLE public.usage_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  conversation_id UUID REFERENCES public.conversations(id) ON DELETE SET NULL,
  kind TEXT NOT NULL CHECK (kind IN ('chat','tts')),
  characters INT NOT NULL DEFAULT 0,
  audio_seconds INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT ON public.usage_logs TO authenticated;
GRANT ALL ON public.usage_logs TO service_role;
ALTER TABLE public.usage_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "usage_owner_read" ON public.usage_logs FOR SELECT TO authenticated
  USING (auth.uid() = user_id OR public.has_role(auth.uid(), 'admin'));
CREATE POLICY "usage_owner_insert" ON public.usage_logs FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = user_id);
CREATE INDEX usage_user_idx ON public.usage_logs(user_id, created_at);

-- Updated_at trigger
CREATE OR REPLACE FUNCTION public.set_updated_at() RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END $$;

CREATE TRIGGER trg_profiles_updated BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_subs_updated BEFORE UPDATE ON public.subscriptions
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_personas_updated BEFORE UPDATE ON public.bot_personalities
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_conv_updated BEFORE UPDATE ON public.conversations
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- New user: create profile, assign user role, give starter subscription
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  INSERT INTO public.profiles (id, display_name, avatar_url)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'name', NEW.raw_user_meta_data->>'full_name', split_part(NEW.email,'@',1)),
    NEW.raw_user_meta_data->>'avatar_url'
  )
  ON CONFLICT (id) DO NOTHING;

  INSERT INTO public.user_roles (user_id, role) VALUES (NEW.id, 'user')
  ON CONFLICT DO NOTHING;

  INSERT INTO public.subscriptions (user_id, plan_id)
  VALUES (NEW.id, 'starter')
  ON CONFLICT (user_id) DO NOTHING;

  RETURN NEW;
END $$;

CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Monthly usage view
CREATE OR REPLACE VIEW public.v_current_usage WITH (security_invoker=true) AS
SELECT
  user_id,
  COALESCE(SUM(characters), 0)::bigint AS characters_used,
  COALESCE(SUM(audio_seconds), 0)::bigint AS audio_seconds_used
FROM public.usage_logs
WHERE created_at >= date_trunc('month', now())
GROUP BY user_id;
GRANT SELECT ON public.v_current_usage TO authenticated;

-- ============================================================
-- migrations/20260630194102_eef52d4b-5ead-4f4d-b6d1-8d8911c8dfc3.sql
-- ============================================================

ALTER FUNCTION public.handle_new_user() SET search_path = public;
ALTER FUNCTION public.set_updated_at() SET search_path = public;

REVOKE EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM PUBLIC, anon, authenticated;

-- ============================================================
-- migrations/20260701000000_settings_and_credits.sql
-- ============================================================
-- User settings: preferred speaker voice + speaker age
CREATE TABLE public.user_settings (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  voice_id UUID REFERENCES public.voices(id) ON DELETE SET NULL,
  speaker_age INT CHECK (speaker_age IS NULL OR (speaker_age BETWEEN 1 AND 120)),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.user_settings TO authenticated;
GRANT ALL ON public.user_settings TO service_role;
ALTER TABLE public.user_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "user_settings_owner_all" ON public.user_settings FOR ALL TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);
CREATE TRIGGER trg_user_settings_updated BEFORE UPDATE ON public.user_settings
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Prepaid credit balance (topped up via crypto)
CREATE TABLE public.credits (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  balance INT NOT NULL DEFAULT 0 CHECK (balance >= 0),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT ON public.credits TO authenticated;
GRANT ALL ON public.credits TO service_role;
ALTER TABLE public.credits ENABLE ROW LEVEL SECURITY;
CREATE POLICY "credits_owner_read" ON public.credits FOR SELECT TO authenticated
  USING (auth.uid() = user_id);
CREATE TRIGGER trg_credits_updated BEFORE UPDATE ON public.credits
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Credit purchase ledger (demo crypto top-ups)
CREATE TABLE public.credit_purchases (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  credits INT NOT NULL,
  amount_usd NUMERIC(10,2) NOT NULL DEFAULT 0,
  asset TEXT NOT NULL DEFAULT 'USDC',
  tx_reference TEXT,
  status TEXT NOT NULL DEFAULT 'confirmed',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT ON public.credit_purchases TO authenticated;
GRANT ALL ON public.credit_purchases TO service_role;
ALTER TABLE public.credit_purchases ENABLE ROW LEVEL SECURITY;
CREATE POLICY "credit_purchases_owner_read" ON public.credit_purchases FOR SELECT TO authenticated
  USING (auth.uid() = user_id);

-- Atomically record a (demo) crypto purchase and credit the balance.
-- SECURITY DEFINER so the balance can only ever change through this audited path.
CREATE OR REPLACE FUNCTION public.purchase_credits(
  _credits INT,
  _amount_usd NUMERIC,
  _asset TEXT,
  _tx_reference TEXT
)
RETURNS INT LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  _uid UUID := auth.uid();
  _new_balance INT;
BEGIN
  IF _uid IS NULL THEN RAISE EXCEPTION 'not authenticated'; END IF;
  IF _credits <= 0 THEN RAISE EXCEPTION 'credits must be positive'; END IF;

  INSERT INTO public.credits (user_id, balance)
  VALUES (_uid, _credits)
  ON CONFLICT (user_id)
  DO UPDATE SET balance = public.credits.balance + EXCLUDED.balance, updated_at = now()
  RETURNING balance INTO _new_balance;

  INSERT INTO public.credit_purchases (user_id, credits, amount_usd, asset, tx_reference)
  VALUES (_uid, _credits, COALESCE(_amount_usd, 0), COALESCE(_asset, 'USDC'), _tx_reference);

  RETURN _new_balance;
END $$;
GRANT EXECUTE ON FUNCTION public.purchase_credits(INT, NUMERIC, TEXT, TEXT) TO authenticated;

-- ============================================================
-- migrations/20260701000001_grant_has_role_execute.sql
-- ============================================================
-- Fix: RLS policies on conversations/messages/bot_personalities/subscriptions call
-- public.has_role(), but the authenticated (and anon) roles were never granted EXECUTE
-- on it. Every policy evaluation therefore failed with SQLSTATE 42501:
--   "permission denied for function has_role".
-- Granting EXECUTE lets the SECURITY DEFINER function be called during policy checks.
GRANT EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) TO authenticated, anon;

-- ============================================================
-- migrations/20260701000002_seed_plans_voices.sql
-- ============================================================
-- Seed reference data required by the app. Without at least the 'starter' plan,
-- the handle_new_user() trigger fails (FK to plans) and sign-up breaks.

INSERT INTO public.plans (id, name, price_monthly, char_quota, audio_seconds_quota, features, display_order) VALUES
  ('starter', 'Starter', 19,  250000,   3600,   '["3 personas","8 voices","Community support"]'::jsonb, 1),
  ('pro',     'Pro',     89,  2000000,  30000,  '["Unlimited personas","All voices","Priority routing","Email support"]'::jsonb, 2),
  ('studio',  'Studio',  299, 10000000, 180000, '["Custom voice cloning","Team seats","SSO","Dedicated channel"]'::jsonb, 3)
ON CONFLICT (id) DO NOTHING;

-- House voices. elevenlabs_id doubles as the OpenAI TTS voice name.
INSERT INTO public.voices (name, elevenlabs_id, tone, preview_text) VALUES
  ('Alloy',   'alloy',   'Neutral · Even-keeled', 'Hello — I am ready when you are.'),
  ('Coral',   'coral',   'Editorial · Confident', 'Three things you need to know today.'),
  ('Echo',    'echo',    'Smooth · Reflective',   'Listen closely. Every word matters.'),
  ('Fable',   'fable',   'Warm · Storyteller',    'Once, a long time ago, in a quiet room.'),
  ('Nova',    'nova',    'Bright · Modern',       'Good morning. Today is going to be useful.'),
  ('Onyx',    'onyx',    'Deep · Authoritative',  'We begin at the top of the hour.'),
  ('Sage',    'sage',    'Calm · Measured',       'Take a breath. We have time.'),
  ('Shimmer', 'shimmer', 'Soft · Late-night',     'Some thoughts are better whispered.')
ON CONFLICT (elevenlabs_id) DO NOTHING;

-- ============================================================
-- migrations/20260701000003_crypto_tx_verification.sql
-- ============================================================
-- Crypto payment verification: credits are granted only after a Tron USDT (TRC-20)
-- transfer is verified on-chain by transaction hash. Replaces the instant demo path.

ALTER TABLE public.credit_purchases
  ADD COLUMN IF NOT EXISTS tx_hash TEXT,
  ADD COLUMN IF NOT EXISTS network TEXT,
  ADD COLUMN IF NOT EXISTS from_address TEXT,
  ADD COLUMN IF NOT EXISTS to_address TEXT,
  ADD COLUMN IF NOT EXISTS amount_crypto NUMERIC;

-- One credit grant per on-chain transaction (replay / double-spend protection).
CREATE UNIQUE INDEX IF NOT EXISTS credit_purchases_tx_hash_uidx
  ON public.credit_purchases (tx_hash) WHERE tx_hash IS NOT NULL;

-- Remove the old instant, client-callable credit function.
DROP FUNCTION IF EXISTS public.purchase_credits(int, numeric, text, text);

-- Verified redeem: callable ONLY by service_role (i.e. our trusted server function
-- after it has verified the transaction on-chain). Never granted to authenticated,
-- so a client cannot mint credits by calling it directly.
CREATE OR REPLACE FUNCTION public.redeem_crypto_payment(
  _user_id UUID,
  _credits INT,
  _amount_usd NUMERIC,
  _asset TEXT,
  _network TEXT,
  _tx_hash TEXT,
  _from_address TEXT,
  _amount_crypto NUMERIC
) RETURNS INT LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE _new_balance INT;
BEGIN
  IF _user_id IS NULL THEN RAISE EXCEPTION 'missing user'; END IF;
  IF _credits <= 0 THEN RAISE EXCEPTION 'credits must be positive'; END IF;
  IF _tx_hash IS NULL OR length(_tx_hash) < 10 THEN RAISE EXCEPTION 'missing tx_hash'; END IF;

  IF EXISTS (SELECT 1 FROM public.credit_purchases WHERE tx_hash = _tx_hash) THEN
    RAISE EXCEPTION 'tx_already_redeemed';
  END IF;

  INSERT INTO public.credits (user_id, balance)
  VALUES (_user_id, _credits)
  ON CONFLICT (user_id)
  DO UPDATE SET balance = public.credits.balance + EXCLUDED.balance, updated_at = now()
  RETURNING balance INTO _new_balance;

  INSERT INTO public.credit_purchases
    (user_id, credits, amount_usd, asset, network, tx_hash, from_address, amount_crypto, status)
  VALUES
    (_user_id, _credits, _amount_usd, _asset, _network, _tx_hash, _from_address, _amount_crypto, 'confirmed');

  RETURN _new_balance;
END $$;

REVOKE ALL ON FUNCTION public.redeem_crypto_payment(UUID,INT,NUMERIC,TEXT,TEXT,TEXT,TEXT,NUMERIC) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.redeem_crypto_payment(UUID,INT,NUMERIC,TEXT,TEXT,TEXT,TEXT,NUMERIC) TO service_role;
